
const accounts = [
  {
    name: 'Nick_owner_of_here',
    password: '1598753aswq',
    borrowing: 0,
  },
];

const books = [
  {
    name:'First',
    author:"Nick_Zhu",
    time:"2024-06-13",
    cata: "Love story",
    description:"The first book in this system, I handly write the fake information about his book. Other books will be generated by ChatGPT, I think it's fine as everything is fake here in this system. P: ",
    thumbs:100,
  },
  {
    name: 'The Enchanted Garden',
    author: 'Avery Holt',
    time: '2024-05-10',
    cata: 'Love story',
    description: 'A tale of romance and mystery in a garden that seems to have a life of its own. The love story between two gardeners unfolds in a magical setting, where every flower has a secret to tell.',
    thumbs:20,
  },
  {
    name: 'Echoes of Time',
    author: 'Jasper Fenwick',
    time: '2024-04-22',
    cata: 'Time travel',
    description: 'An adventure that spans centuries, where a modern-day historian discovers a way to travel back to medieval times. The journey reveals hidden truths about history and the complexities of altering the past.',
    thumbs:31,
  },
  {
    name: 'Whispers of the Ancients',
    author: 'Serena Moor',
    time: '2024-03-15',
    cata: 'Ancient',
    description: 'A gripping narrative set in ancient Egypt, where a young scribe uncovers a conspiracy that could change the course of history. The story explores themes of loyalty, betrayal, and the quest for truth.',
    thumbs:10,
  },
  {
    name: 'The Forgotten War',
    author: 'Elias Reed',
    time: '2024-02-28',
    cata: 'War',
    description: 'A heart-wrenching story of soldiers caught in the chaos of a forgotten war. Their struggles and sacrifices are vividly portrayed, reminding us of the human cost of conflict.',
    thumbs:12,
  },
  {
    name: 'Chronicles of Love',
    author: 'Isla Bennett',
    time: '2024-01-30',
    cata: 'Love story',
    description: 'A poignant love story that spans decades, following the lives of two people whose paths cross and re-cross over the years. Their enduring love faces trials and triumphs, making for an unforgettable read.',
    thumbs:24,
  },
  {
    name: 'A Journey Through History',
    author: 'Finn Gallagher',
    time: '2023-12-14',
    cata: 'History',
    description: 'An immersive journey into the past, exploring significant historical events through the eyes of those who lived them. The book brings history to life with vivid descriptions and compelling narratives.',
    thumbs:42,
  },
  {
    name: 'Timeless Love',
    author: 'Lydia Harper',
    time: '2023-11-11',
    cata: 'Time travel',
    description: 'A romance that defies time, where two lovers from different eras find themselves connected by fate. Their love story is both timeless and unique, challenging the boundaries of time and space.',
    thumbs:41,
  },
  {
    name: 'Battle of the Ages',
    author: 'Nolan Blake',
    time: '2023-10-05',
    cata: 'War',
    description: 'An epic tale of a war that spans generations, focusing on the bravery and resilience of those who fight. The story captures the essence of heroism and the harsh realities of warfare.',
    thumbs:53,
  },
  {
    name: 'The Lost Civilization',
    author: 'Maya Cross',
    time: '2023-09-23',
    cata: 'Ancient',
    description: 'An archaeological adventure that uncovers the secrets of a long-lost civilization. The protagonist’s journey is filled with danger, discovery, and a quest for knowledge that spans millennia.',
    thumbs:55,
  },
  {
    name: 'Tides of History',
    author: 'Ethan Vance',
    time: '2023-08-19',
    cata: 'History',
    description: 'A comprehensive exploration of historical events that shaped the world. The book delves into the causes and effects of major historical milestones, offering a detailed and insightful perspective.',
    thumbs:82,
  }
]

const comments = [
  {
    id: 1,
    content:"A very lovely love story ! It's about Nick finds his job after hard working."
  }
]

const histories = [
  {
    id:1,
    person:'Nick_owner_of_here',
  }
]



module.exports = {
  accounts,
  books,
  comments,
  histories,
};
